project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!readme.md"

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    embed-resources: true
    toc: true
    toc-expand: true

website:
  title: "Example workflow"
  page-navigation: true
  search: 
    location: sidebar
    type: overlay
    show-item-context: true

  sidebar: 
    style: "docked"
    contents:
    - text: "Welcome page"
      href: index.qmd

    - section: "Data analysis"
      contents:
        - text: Sequence classification"
          href: scripts/nanoclass_workflow.qmd

        - text: "OTU table analysis"
          href: scripts/OTU_table_analysis.qmd

  page-footer:
    left: |
      Copyright 2024, Nina Dombrowski