project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!readme.md"

website:
  title: "Example workflow"
  page-navigation: true
  sidebar: 
    style: "docked"
    search: true
    contents:
      - "scripts/nanoclass_workflow.qmd"
  page-footer:
    left: |
      Copyright 2024, Nina Dombrowski

format:
  html:
    embed-resources: true
    toc: true
    toc-location: left

execute:
  eval: false

engine: knitr