project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!readme.md"

website:
  title: "Example workflow"
  page-navigation: true
  sidebar: 
    style: "docked"
    search: true
    contents:
      - "code/nanoclass_workflow.qmd"
  page-footer:
    left: |
      Copyright 2023, Nina Dombrowski